### ISSUE TITLE
Ensure consistency when making `statusUpdates` 

### ISSUE THREAD

**Issue by therealyingtong** [TechLadies/irrc-madwish#44]
Before accepting a `statusUpdate` from some `prevStatus` to `nextStatus`, the backend should check that the relevant student's current `statusID` indeed matches the claimed `prevStatus`.

**Comment by thchia** [comment]
@therealyingtong we could also disallow having both the same statuses for previous and next? Pretty sure that is not a valid configuration.

**Comment by lauratsui** [comment]
Thanks @therealyingtong, we've added some validations in #48
