### ISSUE TITLE
Subscribe to vuex state changes

### ISSUE THREAD

**Issue by therealyingtong** [TechLadies/irrc-madwish#50]
e.g. reload components when status is changed

**Comment by thchia** [comment]
@aelbore is this handled automatically by Vuex? If we are using `mapGetters` it will show the latest state values in the component?

**Comment by aelbore** [comment]
@therealyingtong and @thchia yes, use the `mapGetters` in computed, 
computed is reactive, please see #52 how to use `mapGetters`
