### ISSUE TITLE
Rename variables in components that are re-used in Student / Teacher logic 

### ISSUE THREAD

**Issue by dzldebby** [TechLadies/irrc-madwish#87]
Certain components such as the Status Card components are being re-used for both Student and Teacher.

For example:
1.  `<StatusCardScreening :studentID="teacherID"` could be renamed to `ID="teacherID"`.
2. `StudentProfileCard.vue` is used by both `StudentProfile.vue` and `TeacherProfile.vue`, therefore it can be renamed to `ProfileCard.vue`

**Comment by therealyingtong** [comment]
Closed by #128
